import type { PrizeDefinition } from "./types";

// Small colliders keep the pile readable; material data also sets contact behavior.
export const PRIZE_DEFINITIONS: PrizeDefinition[] = [
  {
    id: "miso",
    name: "Miso Bear",
    model: "bear",
    color: "#d5aa72",
    accent: "#f7e8cb",
    radius: 0.215,
    mass: 0.23,
    friction: 1.15,
    restitution: 0.04,
    material: "plush",
  },
  {
    id: "mochi",
    name: "Mochi Bunny",
    model: "bunny",
    color: "#e9b9bb",
    accent: "#fff0df",
    radius: 0.2,
    mass: 0.2,
    friction: 1.1,
    restitution: 0.04,
    material: "plush",
  },
  {
    id: "sesame",
    name: "Sesame Cat",
    model: "cat",
    color: "#9298b1",
    accent: "#eddfd2",
    radius: 0.205,
    mass: 0.24,
    friction: 1.08,
    restitution: 0.03,
    material: "plush",
  },
  {
    id: "matcha",
    name: "Matcha Frog",
    model: "frog",
    color: "#8aa987",
    accent: "#e4eacb",
    radius: 0.225,
    mass: 0.27,
    friction: 1.2,
    restitution: 0.03,
    material: "plush",
  },
  {
    id: "pippa",
    name: "Pippa Penguin",
    model: "penguin",
    color: "#789bae",
    accent: "#f2e9d7",
    radius: 0.205,
    mass: 0.33,
    friction: 0.75,
    restitution: 0.06,
    material: "rubber",
  },
  {
    id: "yuzu",
    name: "Yuzu Bird",
    model: "bird",
    color: "#dec470",
    accent: "#fbecd0",
    radius: 0.195,
    mass: 0.22,
    friction: 1.1,
    restitution: 0.04,
    material: "plush",
  },
  {
    id: "porcini",
    name: "Porcini",
    model: "mushroom",
    color: "#bd7770",
    accent: "#e8d8b9",
    radius: 0.21,
    mass: 0.35,
    friction: 0.62,
    restitution: 0.05,
    material: "rubber",
  },
  {
    id: "orbit",
    name: "Orbit Capsule",
    model: "capsule",
    color: "#89a6c3",
    accent: "#f2c4a8",
    radius: 0.17,
    mass: 0.38,
    friction: 0.18,
    restitution: 0.13,
    material: "plastic",
  },
  {
    id: "luma",
    name: "Luma Star",
    model: "star",
    color: "#cfb2cb",
    accent: "#eee0b9",
    radius: 0.215,
    mass: 0.25,
    friction: 1.05,
    restitution: 0.03,
    material: "plush",
  },
  {
    id: "pebble",
    name: "Pebble Seal",
    model: "seal",
    color: "#c4c9bf",
    accent: "#f5e8d7",
    radius: 0.215,
    mass: 0.31,
    friction: 0.8,
    restitution: 0.04,
    material: "rubber",
  },
];

const VARIANT_COLORS = [
  "#bdd3c4",
  "#d7adc0",
  "#d8b98b",
  "#a8bdd5",
  "#ceb8d7",
  "#e7cf91",
];
export function prizeDefinition(index: number): PrizeDefinition {
  const base = PRIZE_DEFINITIONS[index % PRIZE_DEFINITIONS.length];
  if (index < PRIZE_DEFINITIONS.length) return base;
  return {
    ...base,
    id: `${base.id}-${Math.floor(index / PRIZE_DEFINITIONS.length)}`,
    color: VARIANT_COLORS[index % VARIANT_COLORS.length],
  };
}
